eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_SERVER_ADDRESS} #http://localhost:8761/eureka
      
okta:
  oauth2:
    issuer: https://dev-34587107.okta.com/oauth2/default
    audience: api://default
